# Generated by Django 5.0.2 on 2024-02-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
                ('tool', models.CharField(max_length=50)),
                ('published_date', models.DateField()),
            ],
        ),
    ]
