# Generated by Django 5.0.2 on 2024-02-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze_texts_dashboard', '0003_remove_comments_search_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='sentiment',
            field=models.CharField(default='neu', max_length=3),
            preserve_default=False,
        ),
    ]
